import { Contact } from './contacts.interface';

export const contactsData: Contact[] = [
  { id : 1,
    firstName: 'John',
    lastName: 'Doe',
    email: 'johndoe@example.com',
    phone: '+1234567890',
    company: 'Example Inc.',
    jobTitle: 'Software Engineer',
    address: '123 Main St',
    city: 'San Francisco',
    country: 'USA',
    state: 'California',
    zipCode: 94105,
  },
  { id :2,
    firstName: 'Badis',
    lastName: 'Beji',
    email: 'badis@example.com',
    phone: '+21671234567',
    company: 'ADS',
    jobTitle: 'Intern',
    address: '1 Rue de la Liberté',
    city: 'Tunis',
    country: 'Tunisia',
    state: 'Tunis',
    zipCode: 1001,
  },
  { id : 3,
    firstName: 'Ahmed',
    lastName: 'Khalfallah',
    email: 'khalfallah@example.com',
    phone: '+21623456789',
    company: 'Tunisian Tech Company',
    jobTitle: 'UI/UX Designer',
    address: '14 Rue des Jardins',
    city: 'Sfax',
    country: 'Tunisia',
    state: 'Sfax',
    zipCode: 3000,
  }
  
];